name: 'Unit Test'

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install
      - name: Run tests
        run: yarn test
